### ISSUE TITLE
Get parameter value from environment parameter or external properies file

### ISSUE THREAD

**Issue by samxzq1983** [wso2-extensions/esb-inbound-kafka#48]
**Description:**
All kakfa parameters' value can not read from environment parameter or external properties file  

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3544
