### ISSUE TITLE
Maven repository artifact id for this extension 

### ISSUE THREAD

**Issue by corrantho** [wso2-extensions/esb-inbound-kafka#54]
**Description:**

Hello,

We would like to use this extension in one of our WSO2 Micro Integrator service. Our build pipeline requires to download our JAR dependencies via maven. 

Could you please share with how to download this dependency via the WSO2 Maven repositories?

Thank you.

Regards,
Anthony

**Comment by steveliem** [comment]
Hi,

Why nobody answered this perfectly normal question?? When I tried to find the maven dependency in the maven public repo I couldn't find anything.

**Comment by anupama-pathirage** [comment]
Moved the question for better visiblity https://github.com/wso2/micro-integrator/issues/3543
