### ISSUE TITLE
Do not update offset when wso2 fails to fetch data from kafka and send it downstream

### ISSUE THREAD

**Issue by zhaowc88** [wso2-extensions/esb-inbound-kafka#55]
Dear author friends,

I currently have a requirement: the link is like this, wso2 takes data from kafka and sends it to the downstream system. Now I want to implement the offset in kafka without updating if wso2 fails to send it downstream.

How do you do that, thank you very much

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3542
